import { GlobalSettings, PageContent } from "./types";

export const defaultContent: PageContent = {
  title: "Sip Society",
  blocks: [
    {
      id: "hero-1",
      type: "hero",
      data: {
        videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
        videoX: 50,
        videoY: 50,
        videoScale: 1,
        overlayOpacity: 0.55,
        videoDesaturate: 0.6,
        tagline: "Slow sips. Bright ideas.",
        showTagline: true,
        taglineStyle: { size: 48, weight: 600, italic: false, x: 0, y: 0 },
        logoScale: 1,
        logoBoxScale: 1,
        logoX: 0,
        logoY: 0,
      },
    },
    {
      id: "brand-1",
      type: "brand-message",
      data: {
        showTopImage: true,
        topImageUrl:
          "https://images.unsplash.com/photo-1445116572660-236099ec97a0?q=80&w=1800&auto=format&fit=crop",
        topImageAlt: "Pouring coffee",
        topImageLinkEnabled: false,
        topImageLinkUrl: "",
        showBgVideo: false,
        bgVideoUrl: "",
        bgVideoX: 50,
        bgVideoY: 50,
        bgVideoScale: 1,
        bgVideoOpacity: 0.4,
        bgVideoFeather: 0.12,
        bgVideoDesaturate: 0.4,
        heading: "Our brand message",
        showHeading: true,
        headingStyle: { size: 12, weight: 600, italic: false, x: 0, y: 0 },
        message:
          "Sip Society is a third place for creatives. Thoughtful drinks, slow moments, and bright ideas.",
        showMessage: true,
        messageStyle: { size: 30, weight: 600, italic: false, x: 0, y: 0 },
        icon: "coffee",
        logoScale: 1,
        logoBoxScale: 1,
        logoX: 0,
        logoY: 0,
        animationType: "reveal",
        animationTrigger: "once",
        animationPlayId: 0,
      },
    },
    {
      id: "triple-1",
      type: "triple-media",
      data: {
        leftTitle: "Seasonal ritual",
        leftTitleStyle: { size: 30, weight: 600, italic: false, x: 0, y: 0 },
        leftBody:
          "Small-lot roasts and curated teas. The bar rotates weekly with new notes.",
        leftBodyStyle: { size: 16, weight: 500, italic: false, x: 0, y: 0 },
        leftAccent: "#c07a4a",
        leftLogoScale: 1,
        leftLogoBoxScale: 1,
        leftLogoX: 0,
        leftLogoY: 0,
        middleMedia: {
          url: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?q=80&w=1600&auto=format&fit=crop",
          alt: "Coffee pour",
          type: "image",
          x: 50,
          y: 50,
          scale: 1,
        },
        rightMedia: {
          url: "https://www.w3schools.com/html/mov_bbb.mp4",
          alt: "Barista motion",
          type: "video",
          x: 50,
          y: 50,
          scale: 1,
        },
        rightMediaCurtainEnabled: true,
        leftBorderEffect: "tracer",
      },
    },
    {
      id: "landscape-1",
      type: "landscape",
      data: {
        media: {
          url: "https://images.unsplash.com/photo-1511920170033-f8396924c348?q=80&w=1800&auto=format&fit=crop",
          alt: "Cafe interior",
          type: "image",
          x: 50,
          y: 50,
          scale: 1,
        },
        caption: "An atmosphere built for slow sips and bright ideas.",
        captionStyle: { size: 18, weight: 600, italic: false, x: 0, y: 0 },
      },
    },
    {
      id: "footer-1",
      type: "footer",
      data: {
        tagline: "Sip Society. Slow sips, bright ideas.",
        showTagline: true,
        taglineStyle: { size: 14, weight: 500, italic: false, x: 0, y: 0 },
        linkStyle: { size: 13, weight: 600, italic: false, x: 0, y: 0 },
        leadText: "Join our list for seasonal drops and cafe events.",
        leadStyle: { size: 16, weight: 600, italic: false, x: 0, y: 0 },
        leadPlaceholder: "Enter your email",
        leadButtonText: "Join",
        showLeadLogo: true,
        links: [
          { label: "Instagram", href: "#" },
          { label: "Menu", href: "/menu" },
          { label: "Email us", href: "mailto:info@sipsociety.us" },
          { label: "Newsletter", href: "#" },
        ],
      },
    },
  ],
};

export const defaultMenuContent: PageContent = {
  title: "Menu",
  blocks: [
    {
      id: "menu-1",
      type: "menu",
      data: {
        heading: "Slow sips, bright ideas.",
        subheading:
          "Seasonal rotations and small-lot offerings. Ask the bar for today's featured beans and rare pours.",
        note: "Menu items below are placeholders. Swap in your real offerings any time.",
        sections: [
          {
            title: "Coffee",
            items: [
              { name: "Vietnamese Phin", detail: "Condensed milk, slow drip", price: "$6" },
              { name: "Cold Brew", detail: "Cacao nibs, orange zest", price: "$5" },
              { name: "Latte", detail: "Oat or whole milk", price: "$5.5" },
            ],
          },
          {
            title: "Espresso",
            items: [
              { name: "Espresso", detail: "Single origin", price: "$3.5" },
              { name: "Cortado", detail: "Equal parts espresso and milk", price: "$4.5" },
              { name: "Affogato", detail: "Espresso over vanilla gelato", price: "$6.5" },
            ],
          },
          {
            title: "Tea",
            items: [
              { name: "Jasmine Green", detail: "Floral, bright", price: "$4" },
              { name: "Oolong", detail: "Roasted, nutty", price: "$4.5" },
              { name: "Chai", detail: "Spiced, creamy", price: "$5" },
            ],
          },
          {
            title: "Bakery",
            items: [
              { name: "Butter Croissant", detail: "Flaky, warm", price: "$4" },
              { name: "Almond Kouign Amann", detail: "Caramelized, rich", price: "$5" },
              { name: "Cinnamon Bun", detail: "Brown sugar glaze", price: "$4.5" },
            ],
          },
        ],
      },
    },
  ],
};

export const defaultGlobals: GlobalSettings = {
  logoText: "Sip Society",
  logoMark: "SS",
  logoImageUrl: "",
  showLogoMark: true,
  showLogoText: true,
  showLogoBox: true,
  logoTextLinkEnabled: false,
  logoTextLinkUrl: "",
  bodyFont: "sans",
  mottoFont: "display",
  brandHeadingFont: "sans",
  brandMessageFont: "display",
  motto: "Slow sips. Bright ideas.",
  brandMessage:
    "Sip Society is a third place for creatives. Thoughtful drinks, slow moments, and bright ideas.",
  logoTextStyle: { size: 12, weight: 600, italic: false, x: 0, y: 0 },
  mottoStyle: { size: 40, weight: 600, italic: false, x: 0, y: 0 },
  brandMessageStyle: { size: 30, weight: 600, italic: false, x: 0, y: 0 },
  borderEnabled: true,
  borderColor: "#e7e2d9",
  borderWidth: 1,
  introEnabled: true,
  introBgFrom: "#0c0a09",
  introBgVia: "#1c1917",
  introBgTo: "#78350f",
  introTextColor: "#fde68a",
  introWipeColor: "#0c0a09",
  introHoldMs: 1400,
  introWipeMs: 700,
  introFadeMs: 700,
  menuButtonText: "MENU",
  menuButtonTextColor: "#1c1917",
  menuButtonBorderColor: "#d6d3d1",
  menuButtonBg: "rgba(255,255,255,0.25)",
  menuButtonFont: "sans",
  menuButtonTextSize: 11,
  menuItemFont: "sans",
  menuItemSize: 18,
  menuItemColor: "#1c1917",
  menuPanelBg: "#ffffff",
  menuPanelTextColor: "#1c1917",
  menuPanelWidthPct: 25,
  menuItems: [
    { id: "nav-brand", label: "Brand", href: "#brand" },
    { id: "nav-media", label: "Media", href: "#media" },
    { id: "nav-atmo", label: "Atmosphere", href: "#landscape" },
    { id: "nav-menu", label: "Menu", href: "/menu" },
  ],
};
