import { AboutContent, GlobalSettings, PageContent } from "./types";

export const defaultContent: PageContent = {
  title: "Sip Society",
  blocks: [
    {
      id: "hero-1",
      type: "hero",
      data: {
        videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
        imageUrl: "",
        videoX: 50,
        videoY: 50,
        videoScale: 1,
        imageX: 50,
        imageY: 50,
        imageScale: 1,
        overlayOpacity: 0.55,
        videoDesaturate: 0.6,
        tagline: "Slow sips. Bright ideas.",
        showTagline: true,
        taglineRich: false,
        taglineStyle: { size: 48, weight: 600, italic: false, x: 0, y: 0 },
        logoScale: 1,
        logoBoxScale: 1,
        logoX: 0,
        logoY: 0,
      },
    },
    {
      id: "brand-1",
      type: "brand-message",
      data: {
        showTopImage: true,
        topImageUrl:
          "https://images.unsplash.com/photo-1445116572660-236099ec97a0?q=80&w=1800&auto=format&fit=crop",
        topImageAlt: "Pouring coffee",
        topImageLinkEnabled: false,
        topImageLinkUrl: "",
        showBgVideo: false,
        bgVideoUrl: "",
        bgVideoX: 50,
        bgVideoY: 50,
        bgVideoScale: 1,
        bgVideoOpacity: 0.4,
        bgVideoFeather: 0.12,
        bgVideoDesaturate: 0.4,
        heading: "Our brand message",
        headingRich: false,
        showHeading: true,
        headingStyle: { size: 12, weight: 600, italic: false, x: 0, y: 0 },
        message:
          "Sip Society is a third place for creatives. Thoughtful drinks, slow moments, and bright ideas.",
        messageRich: true,
        showMessage: true,
        messageStyle: { size: 30, weight: 600, italic: false, x: 0, y: 0 },
        icon: "coffee",
        logoScale: 1,
        logoBoxScale: 1,
        logoX: 0,
        logoY: 0,
        animationType: "reveal",
        animationTrigger: "once",
        animationPlayId: 0,
      },
    },
    {
      id: "triple-1",
      type: "triple-media",
      data: {
        leftTitle: "Seasonal ritual",
        leftTitleRich: true,
        leftTitleStyle: { size: 30, weight: 600, italic: false, x: 0, y: 0 },
        leftBody:
          "Small-lot roasts and curated teas. The bar rotates weekly with new notes.",
        leftBodyRich: true,
        leftBodyStyle: { size: 16, weight: 500, italic: false, x: 0, y: 0 },
        leftAccent: "#c07a4a",
        leftLogoScale: 1,
        leftLogoBoxScale: 1,
        leftLogoMaxPx: 180,
        leftLogoX: 0,
        leftLogoY: 0,
        middleMedia: {
          url: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?q=80&w=1600&auto=format&fit=crop",
          alt: "Coffee pour",
          type: "image",
          x: 50,
          y: 50,
          scale: 1,
        },
        rightMedia: {
          url: "https://www.w3schools.com/html/mov_bbb.mp4",
          alt: "Barista motion",
          type: "video",
          x: 50,
          y: 50,
          scale: 1,
        },
        rightMediaCurtainEnabled: true,
        leftBorderEffect: "tracer",
      },
    },
    {
      id: "landscape-1",
      type: "landscape",
      data: {
        media: {
          url: "https://images.unsplash.com/photo-1511920170033-f8396924c348?q=80&w=1800&auto=format&fit=crop",
          alt: "Cafe interior",
          type: "image",
          x: 50,
          y: 50,
          scale: 1,
        },
        caption: "An atmosphere built for slow sips and bright ideas.",
        captionRich: false,
        captionStyle: { size: 18, weight: 600, italic: false, x: 0, y: 0 },
      },
    },
    {
      id: "footer-1",
      type: "footer",
      data: {
        tagline: "Sip Society. Slow sips, bright ideas.",
        showTagline: true,
        taglineStyle: { size: 14, weight: 500, italic: false, x: 0, y: 0 },
        linkStyle: { size: 13, weight: 600, italic: false, x: 0, y: 0 },
        leadText: "Join our list for seasonal drops and cafe events.",
        leadTextRich: false,
        leadStyle: { size: 16, weight: 600, italic: false, x: 0, y: 0 },
        joinLabel: "Join us",
        leadPlaceholder: "Enter your email",
        leadButtonText: "Join",
        leadButtonTextRich: false,
        showLeadLogo: true,
        links: [
          { label: "Instagram", href: "#" },
          { label: "Menu", href: "/menu" },
          { label: "Email us", href: "mailto:info@sipsociety.us" },
          { label: "Newsletter", href: "#" },
        ],
      },
    },
  ],
};

export const defaultMenuContent: PageContent = {
  title: "Menu",
  blocks: [
    {
      id: "menu-1",
      type: "menu",
      data: {
        heading: "Slow sips, bright ideas.",
        subheading:
          "Seasonal rotations and small-lot offerings. Ask the bar for today's featured beans and rare pours.",
        note: "Menu items below are placeholders. Swap in your real offerings any time.",
        showPrices: true,
        sections: [
          {
            id: "menu-coffee",
            title: "Coffee",
            items: [
              {
                id: "menu-coffee-1",
                name: "Vietnamese Phin",
                detail: "Condensed milk, slow drip",
                price: "$6",
                namePos: { x: 0, y: 0 },
                detailPos: { x: 0, y: 20 },
                pricePos: { x: 220, y: 0 },
              },
              {
                id: "menu-coffee-2",
                name: "Cold Brew",
                detail: "Cacao nibs, orange zest",
                price: "$5",
                namePos: { x: 0, y: 64 },
                detailPos: { x: 0, y: 84 },
                pricePos: { x: 220, y: 64 },
              },
              {
                id: "menu-coffee-3",
                name: "Latte",
                detail: "Oat or whole milk",
                price: "$5.5",
                namePos: { x: 0, y: 128 },
                detailPos: { x: 0, y: 148 },
                pricePos: { x: 220, y: 128 },
              },
            ],
          },
          {
            id: "menu-espresso",
            title: "Espresso",
            items: [
              {
                id: "menu-espresso-1",
                name: "Espresso",
                detail: "Single origin",
                price: "$3.5",
                namePos: { x: 0, y: 0 },
                detailPos: { x: 0, y: 20 },
                pricePos: { x: 220, y: 0 },
              },
              {
                id: "menu-espresso-2",
                name: "Cortado",
                detail: "Equal parts espresso and milk",
                price: "$4.5",
                namePos: { x: 0, y: 64 },
                detailPos: { x: 0, y: 84 },
                pricePos: { x: 220, y: 64 },
              },
              {
                id: "menu-espresso-3",
                name: "Affogato",
                detail: "Espresso over vanilla gelato",
                price: "$6.5",
                namePos: { x: 0, y: 128 },
                detailPos: { x: 0, y: 148 },
                pricePos: { x: 220, y: 128 },
              },
            ],
          },
          {
            id: "menu-tea",
            title: "Tea",
            items: [
              {
                id: "menu-tea-1",
                name: "Jasmine Green",
                detail: "Floral, bright",
                price: "$4",
                namePos: { x: 0, y: 0 },
                detailPos: { x: 0, y: 20 },
                pricePos: { x: 220, y: 0 },
              },
              {
                id: "menu-tea-2",
                name: "Oolong",
                detail: "Roasted, nutty",
                price: "$4.5",
                namePos: { x: 0, y: 64 },
                detailPos: { x: 0, y: 84 },
                pricePos: { x: 220, y: 64 },
              },
              {
                id: "menu-tea-3",
                name: "Chai",
                detail: "Spiced, creamy",
                price: "$5",
                namePos: { x: 0, y: 128 },
                detailPos: { x: 0, y: 148 },
                pricePos: { x: 220, y: 128 },
              },
            ],
          },
          {
            id: "menu-bakery",
            title: "Bakery",
            items: [
              {
                id: "menu-bakery-1",
                name: "Butter Croissant",
                detail: "Flaky, warm",
                price: "$4",
                namePos: { x: 0, y: 0 },
                detailPos: { x: 0, y: 20 },
                pricePos: { x: 220, y: 0 },
              },
              {
                id: "menu-bakery-2",
                name: "Almond Kouign Amann",
                detail: "Caramelized, rich",
                price: "$5",
                namePos: { x: 0, y: 64 },
                detailPos: { x: 0, y: 84 },
                pricePos: { x: 220, y: 64 },
              },
              {
                id: "menu-bakery-3",
                name: "Cinnamon Bun",
                detail: "Brown sugar glaze",
                price: "$4.5",
                namePos: { x: 0, y: 128 },
                detailPos: { x: 0, y: 148 },
                pricePos: { x: 220, y: 128 },
              },
            ],
          },
        ],
      },
    },
  ],
};

export const defaultGalleryContent: PageContent = {
  title: "Gallery",
  blocks: [],
  gallery: {
    heading: "Gallery",
    subheading: "Customer favorites, cafe moments, and rotating seasonal drops.",
    heroLeft: {
      url: "",
      alt: "",
      type: "image",
      x: 50,
      y: 50,
      scale: 1,
    },
    heroRight: {
      url: "",
      alt: "",
      type: "video",
      x: 50,
      y: 50,
      scale: 1,
    },
    rows: [
      {
        id: "gallery-row-1",
        items: Array.from({ length: 5 }).map((_, index) => ({
          id: `gallery-1-${index + 1}`,
          url: "",
          alt: "",
          comment: "",
          commentDisplay: "hover",
        })),
      },
      {
        id: "gallery-row-2",
        items: Array.from({ length: 5 }).map((_, index) => ({
          id: `gallery-2-${index + 1}`,
          url: "",
          alt: "",
          comment: "",
          commentDisplay: "hover",
        })),
      },
    ],
    commentX: 8,
    commentY: 82,
    commentSize: 12,
    commentColor: "#ffffff",
    commentFont: "sans",
    commentOpacity: 0.9,
    tileGap: 16,
    favoriteThreshold: 12,
  },
};

export const defaultContactContent: PageContent = {
  title: "Contact us",
  blocks: [],
  contact: {
    backgroundUrl:
      "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?q=80&w=2000&auto=format&fit=crop",
    backgroundType: "image",
    backgroundX: 50,
    backgroundY: 50,
    backgroundScale: 1,
    heading: "Contact us",
    body: "Plan a tasting, reserve the lounge, or just say hi. We reply within 1 business day.",
    label: "Your email",
    placeholder: "you@email.com",
    messageLabel: "Your message",
    messagePlaceholder: "Type your message...",
    buttonText: "Send message",
    boxColor: "#ffffff",
    boxOpacity: 0.92,
    boxTextColor: "#1c1917",
    buttonColor: "#111827",
    buttonTextColor: "#ffffff",
  },
};

export const defaultAboutContent: AboutContent = {
  heroImageUrl:
    "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?q=80&w=2000&auto=format&fit=crop",
  heroVideoUrl: "",
  heroMediaType: "image",
  heroOverlayOpacity: 0.55,
  heroLogoUrl: "",
  heroLogoScale: 1,
  heroLogoX: 0,
  heroLogoY: 0,
  heroTitle: "About us",
  heroBody:
    "Sip Society is a third place for makers, dreamers, and slow sippers. We build thoughtful moments with great coffee, warm light, and a community that feels like home.",
  heroTitleAnimation: { type: "move-up", trigger: "once", playId: 0 },
  heroBodyAnimation: { type: "fade", trigger: "once", playId: 0 },
  heroLogoAnimation: { type: "move-right", trigger: "once", playId: 0 },
  sectionTitle: "Our story",
  sections: [
    {
      id: "about-1",
      mediaType: "image",
      mediaUrl:
        "https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?q=80&w=1800&auto=format&fit=crop",
      mediaAlt: "Barista pouring coffee",
      mediaSide: "left",
      heading: "Built around people",
      body:
        "We started as a small crew obsessed with craft and hospitality. Every drink and detail is designed to make you feel seen, welcome, and inspired.",
      mediaAnimation: { type: "move-left", trigger: "once", playId: 0 },
      textAnimation: { type: "move-up", trigger: "once", playId: 0 },
    },
    {
      id: "about-2",
      mediaType: "video",
      mediaUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
      mediaAlt: "Cafe motion",
      mediaSide: "right",
      heading: "Slow rituals, bright ideas",
      body:
        "We believe in slow mornings, big conversations, and the ritual of a beautifully made drink. Sip Society is where those moments live.",
      mediaAnimation: { type: "move-right", trigger: "once", playId: 0 },
      textAnimation: { type: "move-up", trigger: "once", playId: 0 },
    },
    {
      id: "about-3",
      mediaType: "image",
      mediaUrl:
        "https://images.unsplash.com/photo-1504674900247-0877df9cc836?q=80&w=1800&auto=format&fit=crop",
      mediaAlt: "Community gathering",
      mediaSide: "left",
      heading: "Designed for community",
      body:
        "Our spaces are built for collaboration and connection. We host pop-ups, workshops, and late-night conversations that turn strangers into friends.",
      mediaAnimation: { type: "zoom-in", trigger: "once", playId: 0 },
      textAnimation: { type: "move-up", trigger: "once", playId: 0 },
    },
  ],
};

export const defaultGlobals: GlobalSettings = {
  logoText: "Sip Society",
  logoMark: "SS",
  logoImageUrl: "",
  showLogoMark: true,
  showLogoText: true,
  showLogoBox: true,
  logoTextLinkEnabled: false,
  logoTextLinkUrl: "",
  bodyFont: "sans",
  mottoFont: "display",
  brandHeadingFont: "sans",
  brandMessageFont: "display",
  motto: "Slow sips. Bright ideas.",
  brandMessage:
    "Sip Society is a third place for creatives. Thoughtful drinks, slow moments, and bright ideas.",
  brandMessageRich: true,
  logoTextStyle: { size: 12, weight: 600, italic: false, x: 0, y: 0 },
  mottoStyle: { size: 40, weight: 600, italic: false, x: 0, y: 0 },
  brandMessageStyle: { size: 30, weight: 600, italic: false, x: 0, y: 0 },
  borderEnabled: true,
  borderColor: "#e7e2d9",
  borderWidth: 1,
  introEnabled: true,
  introBgFrom: "#0c0a09",
  introBgVia: "#1c1917",
  introBgTo: "#78350f",
  introTextColor: "#fde68a",
  introWipeColor: "#0c0a09",
  introHoldMs: 1400,
  introWipeMs: 700,
  introFadeMs: 700,
  introAnimationType: "wipe",
  introLogoScale: 1,
  introLogoX: 0,
  introLogoY: 0,
  introLogoTextRich: true,
  introMottoRich: true,
  introLogoTextHtml: "",
  introMottoHtml: "",
  introBody:
    "A modern coffee and tea collective for makers, listeners, and late-night sketches.",
  introBodyRich: true,
  introBodyHtml: "",
  introBody2: "Come for the ritual, stay for the quiet ideas.",
  introBody2Rich: true,
  introBody2Html: "",
  menuButtonText: "MENU",
  menuButtonTextColor: "#1c1917",
  menuButtonBorderColor: "#d6d3d1",
  menuButtonBg: "rgba(255,255,255,0.25)",
  menuButtonFont: "sans",
  menuButtonTextSize: 11,
  menuItemFont: "sans",
  menuItemSize: 18,
  menuItemColor: "#1c1917",
  menuPanelBg: "#ffffff",
  menuPanelTextColor: "#1c1917",
  menuPanelWidthPct: 25,
  facebookUrl: "",
  instagramUrl: "",
  menuItems: [
    { id: "nav-home", label: "Home", href: "/" },
    { id: "nav-about", label: "About us", href: "/about-us" },
    { id: "nav-menu", label: "Menu", href: "/menu" },
    { id: "nav-gallery", label: "Gallery", href: "/gallery" },
    { id: "nav-career", label: "Career", href: "/career" },
    { id: "nav-contact", label: "Contact us", href: "/contact-us" },
  ],
  adminNotes: [],
};

export const defaultCareerContent = {
  heroImageUrl: "/career-hero.svg",
  heroImageDesaturate: 0.2,
  heroEyebrow: "Careers",
  heroEyebrowStyle: { size: 12, weight: 600, italic: false, x: 0, y: 0 },
  heroHeadline: "Brew your next chapter with Sip Society.",
  heroHeadlineStyle: { size: 48, weight: 600, italic: false, x: 0, y: 0 },
  heroBody:
    "We are building a hospitality team that feels like a community. Apply for an open role, share your resume, and we will follow up quickly.",
  heroBodyStyle: { size: 16, weight: 500, italic: false, x: 0, y: 0 },
  rolesHeading: "Open roles",
  rolesHeadingStyle: { size: 26, weight: 600, italic: false, x: 0, y: 0 },
  rolesEmptyText: "New roles will be posted soon.",
  rolesEmptyStyle: { size: 14, weight: 500, italic: false, x: 0, y: 0 },
  applyHeading: "Apply for a role",
  applyHeadingStyle: { size: 22, weight: 600, italic: false, x: 0, y: 0 },
  applyBody:
    "Share your information, select a position, and include a resume link or upload a file. We review every application.",
  applyBodyStyle: { size: 14, weight: 500, italic: false, x: 0, y: 0 },
  applyButtonText: "Apply for this role",
  applyButtonStyle: { size: 12, weight: 600, italic: false, x: 0, y: 0 },
  applyCardBgColor: "#ffffff",
  applyCardBgOpacity: 0.12,
  applyCardTextColor: "#ffffff",
  formCardBgColor: "#ffffff",
  formCardBgOpacity: 0.9,
  formCardTextColor: "#1c1917",
};
